---
- name: Install unbound
  ansible.builtin.package:
    name: dns/unbound
    state: present

- name: Local DNS Entries
  ansible.builtin.template:
    src: localdns.conf.j2
    dest: /usr/local/etc/unbound/localdns.conf
    owner: unbound
    group: unbound
    mode: '0644'
  notify: restart_unbound

- name: Local blocklist
  ansible.builtin.template:
    src: block.conf.j2
    dest: /usr/local/etc/unbound/block.conf
    owner: unbound
    group: unbound
    mode: '0644'
  notify: restart_unbound

- name: Make sure adblock file exists
  ansible.builtin.file:
    state: touch
    modification_time: preserve
    access_time: preserve
    dest: /usr/local/etc/unbound/adblock.conf
    owner: unbound
    group: unbound
    mode: '0644'

- name: Unbound configuration
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /usr/local/etc/unbound/unbound.conf
    owner: unbound
    group: unbound
    mode: '0644'
    validate: unbound-checkconf -f %s
  notify: restart_unbound

- name: Remove Sample Configuration
  ansible.builtin.file:
    path: /usr/local/etc/unbound/unbound.conf.sample
    state: absent

- name: Make sure unbound is running and enabled
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: yes

- name: Update adblock list
  ansible.builtin.cron:
    name: Update Adblock list
    weekday: '6'
    hour: '4'
    minute: '20'
    user: unbound
    job: >
      fetch https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -o - |
      grep -v "#" | grep "0.0.0.0" |
      awk '{print "local-zone: \""$2"\" always_nxdomain"}' >
      /usr/local/etc/unbound/adblock.conf &&
      kill -HUP `cat /usr/local/etc/unbound/unbound.pid`
